# One stock analysis
- https://pypi.org/project/yfinance/
- https://medium.com/@josue.monte/why-adj-close-disappeared-in-yfinance-and-how-to-adapt-6baebf1939f6

In [1]:
# pip install ffn bt yfinance pandas matplotlib

import pandas as pd
import yfinance as yf
import ffn
import bt

In [5]:
help(yf.download)

Help on function download in module yfinance.multi:

download(tickers, start=None, end=None, actions=False, threads=True, ignore_tz=None, group_by='column', auto_adjust=True, back_adjust=False, repair=False, keepna=False, progress=True, period=None, interval='1d', prepost=False, rounding=False, timeout=10, session=None, multi_level_index=True) -> Optional[pandas.core.frame.DataFrame]
    Download yahoo tickers
    :Parameters:
        tickers : str, list
            List of tickers to download
        period : str
            Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
            Default: 1mo
            Either Use period parameter or use start and end
        interval : str
            Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
            Intraday data cannot extend last 60 days
        start: str
            Download start date string (YYYY-MM-DD) or _datetime, inclusive.
            Default is 99 years ago
            E.g. for start="2020-01-01", the first data point will be on "2020-01-01"
        end: str
            Download end date string (YYYY-MM-DD) or _datetime, exclusive.
            Default is now
            E.g. for end="2023-01-01", the last data point will be on "2022-12-31"
        group_by : str
            Group by 'ticker' or 'column' (default)
        prepost : bool
            Include Pre and Post market data in results?
            Default is False
        auto_adjust: bool
            Adjust all OHLC automatically? Default is True
        repair: bool
            Detect currency unit 100x mixups and attempt repair
            Default is False
        keepna: bool
            Keep NaN rows returned by Yahoo?
            Default is False
        actions: bool
            Download dividend + stock splits data. Default is False
        threads: bool / int
            How many threads to use for mass downloading. Default is True
        ignore_tz: bool
            When combining from different timezones, ignore that part of datetime.
            Default depends on interval. Intraday = False. Day+ = True.
        rounding: bool
            Optional. Round values to 2 decimal places?
        timeout: None or float
            If not None stops waiting for a response after given number of
            seconds. (Can also be a fraction of a second e.g. 0.01)
        session: None or Session
            Optional. Pass your own session object to be used for all requests
        multi_level_index: bool
            Optional. Always return a MultiIndex DataFrame? Default is True

In [12]:
#px = yf.download("SBIN.NS", start="2015-01-01")["Adj Close"].dropna()
tickers = ["SBIN.NS","ICICIBANK.NS"]
px = yf.download(tickers, start="2020-01-01")
px.tail()

[*********************100%***********************]  2 of 2 completed

Price             Close                     High                      Low  \
Ticker     ICICIBANK.NS     SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS
Date
2025-12-26  1350.400024  966.299988  1362.000000  971.000000  1348.500000
2025-12-29  1343.300049  965.049988  1355.699951  968.900024  1341.500000
2025-12-30  1342.500000  973.450012  1347.099976  976.200012  1338.099976
2025-12-31  1342.900024  982.200012  1350.000000  985.650024  1339.500000
2026-01-01  1338.000000  984.750000  1348.400024  987.650024  1336.000000

Price                          Open                   Volume
Ticker         SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS   SBIN.NS
Date
2025-12-26  964.750000  1356.500000  968.950012      2812144   3286321
2025-12-29  961.450012  1352.099976  966.900024      6057201   5267233
2025-12-30  959.500000  1343.300049  963.000000     18621277  15030644
2025-12-31  973.500000  1342.800049  975.250000      6150634   5807630
2026-01-01  980.349976  1343.900024  983.200012      4179311   4328348

In [27]:
# Check the columns
print(px.columns)  # Output: ['Close', 'High','Low', 'Open', 'Volume']

MultiIndex([( 'Close', 'ICICIBANK.NS'),
            ( 'Close',      'SBIN.NS'),
            (  'High', 'ICICIBANK.NS'),
            (  'High',      'SBIN.NS'),
            (   'Low', 'ICICIBANK.NS'),
            (   'Low',      'SBIN.NS'),
            (  'Open', 'ICICIBANK.NS'),
            (  'Open',      'SBIN.NS'),
            ('Volume', 'ICICIBANK.NS'),
            ('Volume',      'SBIN.NS')],
           names=['Price', 'Ticker'])

In [13]:
px.name = "SBIN"
px.head()

Price             Close                     High                      Low  \
Ticker     ICICIBANK.NS     SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS
Date
2020-01-01   519.137878  308.602600   524.699206  309.986675   518.122343
2020-01-02   522.861511  313.077698   524.118902  313.585209   518.267371
2020-01-03   521.169006  307.910522   523.055034  311.832068   518.654342
2020-01-06   508.450470  294.346619   519.621474  306.065132   506.612790
2020-01-07   505.742462  293.792938   518.025698  301.728306   504.533478

Price                          Open                   Volume
Ticker         SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS   SBIN.NS
Date
2020-01-01  306.480335   522.184543  308.833279      7642793  17379320
2020-01-02  307.587551   518.412473  308.648670     10264223  20324236
2020-01-03  306.341893   520.346921  311.832068      9594690  21853208
2020-01-06  293.147098   519.621474  306.065132     12534334  35645325
2020-01-07  291.024789   513.866803  299.375390     16101835  50966826

In [23]:
close = yf.download(tickers, start="2025-01-01", period="1y", auto_adjust=True)

[*********************100%***********************]  2 of 2 completed

In [24]:
close

Price             Close                     High                      Low  \
Ticker     ICICIBANK.NS     SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS
Date
2025-01-01  1273.821167  777.586426  1283.099550  782.929158  1257.397841
2025-01-02  1280.717896  785.428955  1283.496504  786.605346  1268.611359
2025-01-03  1255.363525  777.782471  1278.137748  793.565529  1252.584917
2025-01-06  1254.420776  761.117126  1267.966283  781.899771  1247.375165
2025-01-07  1269.454834  763.420837  1279.080513  768.420423  1256.802460
...                 ...         ...          ...         ...          ...
2025-12-25  1359.800049  968.950012  1359.800049  968.950012  1359.800049
2025-12-26  1350.400024  966.299988  1362.000000  971.000000  1348.500000
2025-12-29  1343.300049  965.049988  1355.699951  968.900024  1341.500000
2025-12-30  1342.500000  973.450012  1347.099976  976.200012  1338.099976
2025-12-31  1342.900024  982.200012  1350.000000  985.650024  1339.500000

Price                          Open                   Volume
Ticker         SBIN.NS ICICIBANK.NS     SBIN.NS ICICIBANK.NS   SBIN.NS
Date
2025-01-01  773.959246  1271.836481  779.890144      4705399   7273098
2025-01-02  771.508460  1275.260009  779.350986      7433222  11398319
2025-01-03  776.557076  1276.351482  785.428921     11194997  13336514
2025-01-06  757.931100  1258.340604  781.703756      7504047  11419367
2025-01-07  759.597582  1256.802460  764.499161      7539758   9669152
...                ...          ...         ...          ...       ...
2025-12-25  968.950012  1359.800049  968.950012            0         0
2025-12-26  964.750000  1356.500000  968.950012      2812144   3286321
2025-12-29  961.450012  1352.099976  966.900024      6057201   5267233
2025-12-30  959.500000  1343.300049  963.000000     18621277  15030644
2025-12-31  973.500000  1342.800049  975.250000      6150634   5807630

[251 rows x 10 columns]

In [25]:
rets = px.to_returns()
rets

Price             Close                   High                    Low  \
Ticker     ICICIBANK.NS   SBIN.NS ICICIBANK.NS   SBIN.NS ICICIBANK.NS
Date
2020-01-01          NaN       NaN          NaN       NaN          NaN
2020-01-02     0.007173  0.014501    -0.001106  0.011609     0.000280
2020-01-03    -0.003237 -0.016504    -0.002030 -0.005591     0.000747
2020-01-06    -0.024404 -0.044051    -0.006564 -0.018494    -0.023217
2020-01-07    -0.005326 -0.001881    -0.003071 -0.014170    -0.004104
...                 ...       ...          ...       ...          ...
2025-12-26    -0.006913 -0.002735     0.001618  0.002116    -0.008310
2025-12-29    -0.005258 -0.001294    -0.004626 -0.002163    -0.005191
2025-12-30    -0.000596  0.008704    -0.006344  0.007534    -0.002534
2025-12-31     0.000298  0.008989     0.002153  0.009680     0.001046
2026-01-01    -0.003649  0.002596    -0.001185  0.002029    -0.002613

Price                        Open                 Volume
Ticker       SBIN.NS ICICIBANK.NS   SBIN.NS ICICIBANK.NS   SBIN.NS
Date
2020-01-01       NaN          NaN       NaN          NaN       NaN
2020-01-02  0.003613    -0.007224 -0.000598     0.342994  0.169449
2020-01-03 -0.004050     0.003731  0.010314    -0.065230  0.075229
2020-01-06 -0.043072    -0.001394 -0.018494     0.306382  0.631126
2020-01-07 -0.007240    -0.011075 -0.021857     0.284618  0.429832
...              ...          ...       ...          ...       ...
2025-12-26 -0.004335    -0.002427  0.000000          inf       inf
2025-12-29 -0.003421    -0.003244 -0.002116     1.153944  0.602775
2025-12-30 -0.002028    -0.006508 -0.004034     2.074238  1.853613
2025-12-31  0.014591    -0.000372  0.012721    -0.669699 -0.613614
2026-01-01  0.007036     0.000819  0.008152    -0.320507 -0.254714

[1490 rows x 10 columns]

## Multi to Single Ticker

In [58]:
tickers = ["SBIN.NS","ICICIBANK.NS",'HDFCBANK.NS']

In [64]:
options1 = {'period': '2y', 'interval': '1d', 'group_by': 'ticker','multi_level_index': False, 'progress': False}
options2 = {'period': '2y', 'interval': '1d', 'auto_adjust': False,'progress': False}

In [66]:
raw = yf.download(tickers, options1)
data1 = { t.replace(".NS", ""): raw[t].dropna(how="all")
    for t in tickers}
data1

[*********************100%***********************]  3 of 3 completed

3 Failed downloads:
['ICICIBANK.NS', 'HDFCBANK.NS', 'SBIN.NS']: ValueError("Unable to parse input dt {'period': '2y', 'interval': '1d', 'group_by': 'ticker', 'multi_level_index': False, 'progress': False} of type <class 'dict'>")

KeyError: 'SBIN.NS'

In [60]:
data2 = {   t.replace(".NS", ""): yf.download(t, **options)
    for t in tickers}

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [61]:
data

{'SBIN':                SBIN.NS     SBIN.NS     SBIN.NS     SBIN.NS   SBIN.NS
 Date
 2024-01-02  618.355770  624.767372  611.124666  616.523926  15164482
 2024-01-03  616.427515  624.767412  613.004804  620.380554  14571772
 2024-01-04  619.464591  623.224788  615.752647  619.705627  13883388
 2024-01-05  621.874963  628.382957  614.884896  618.934326  15984585
 2024-01-08  617.054239  621.874975  602.640226  604.520325  14739531
 ...                ...         ...         ...         ...       ...
 2025-12-29  966.900024  968.900024  961.450012  965.049988   5267233
 2025-12-30  963.000000  976.200012  959.500000  973.450012  15030644
 2025-12-31  975.250000  985.650024  973.500000  982.200012   5807630
 2026-01-01  983.200012  987.650024  980.349976  984.750000   4328348
 2026-01-02  984.500000  993.000000  983.950012  991.200012   3750967

 [498 rows x 5 columns],
 'ICICIBANK':             ICICIBANK.NS  ICICIBANK.NS  ICICIBANK.NS  ICICIBANK.NS  \
 Date
 2024-01-02    980.921367    981.560909    964.441495    966.409241
 2024-01-03    968.819839    972.066609    959.374622    968.180298
 2024-01-04    970.492381    973.198032    966.064952    971.230286
 2024-01-05    972.066533    982.200413    967.934255    977.674622
 2024-01-08    977.969745    982.102023    964.490673    966.163269
 ...                  ...           ...           ...           ...
 2025-12-29   1352.099976   1355.699951   1341.500000   1343.300049
 2025-12-30   1343.300049   1347.099976   1338.099976   1342.500000
 2025-12-31   1342.800049   1350.000000   1339.500000   1342.900024
 2026-01-01   1343.900024   1348.400024   1336.000000   1338.000000
 2026-01-02   1338.000000   1351.699951   1336.300049   1351.199951

             ICICIBANK.NS
 Date
 2024-01-02      16263825
 2024-01-03      16826752
 2024-01-04      22789140
 2024-01-05      14875499
 2024-01-08       8393164
 ...                  ...
 2025-12-29       6057201
 2025-12-30      18621277
 2025-12-31       6150634
 2026-01-01       4179311
 2026-01-02       4501826

 [498 rows x 5 columns],
 'HDFCBANK':             HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS
 Date
 2024-01-02   826.781764   828.728507   821.866191   826.927734     29242092
 2024-01-03   828.339180   829.653208   812.254191   814.176636     28389762
 2024-01-04   816.658698   824.907997   813.105868   822.912598     26734056
 2024-01-05   821.111889   829.750561   811.840501   818.702759     31889470
 2024-01-08   816.902037   818.775765   807.898350   809.577393     17998470
 ...                 ...          ...          ...          ...          ...
 2025-12-29   993.099976   997.400024   987.200012   991.700012     13545749
 2025-12-30   990.200012   995.000000   982.200012   990.900024     33155849
 2025-12-31   991.000000   997.599976   987.599976   991.200012     10963454
 2026-01-01   993.500000   997.549988   989.500000   991.150024      7132074
 2026-01-02   991.150024  1000.849976   988.799988   999.650024      7129098

 [498 rows x 5 columns]}

In [63]:
data['SBIN'].head()

               SBIN.NS     SBIN.NS     SBIN.NS     SBIN.NS   SBIN.NS
Date
2024-01-02  618.355770  624.767372  611.124666  616.523926  15164482
2024-01-03  616.427515  624.767412  613.004804  620.380554  14571772
2024-01-04  619.464591  623.224788  615.752647  619.705627  13883388
2024-01-05  621.874963  628.382957  614.884896  618.934326  15984585
2024-01-08  617.054239  621.874975  602.640226  604.520325  14739531

In [31]:
out = {t: yf.download(t, **options) for t in tickers}

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [40]:
type(out)

dict

In [47]:
out

{'SBIN.NS':                SBIN.NS     SBIN.NS     SBIN.NS     SBIN.NS   SBIN.NS
 Date
 2024-01-02  618.355831  624.767434  611.124727  616.523987  15164482
 2024-01-03  616.427515  624.767412  613.004804  620.380554  14571772
 2024-01-04  619.464591  623.224788  615.752647  619.705627  13883388
 2024-01-05  621.875025  628.383019  614.884957  618.934387  15984585
 2024-01-08  617.054239  621.874975  602.640226  604.520325  14739531
 ...                ...         ...         ...         ...       ...
 2025-12-29  966.900024  968.900024  961.450012  965.049988   5267233
 2025-12-30  963.000000  976.200012  959.500000  973.450012  15030644
 2025-12-31  975.250000  985.650024  973.500000  982.200012   5807630
 2026-01-01  983.200012  987.650024  980.349976  984.750000   4328348
 2026-01-02  984.500000  993.000000  983.950012  990.700012   3579955

 [498 rows x 5 columns],
 'ICICIBANK.NS':             ICICIBANK.NS  ICICIBANK.NS  ICICIBANK.NS  ICICIBANK.NS  \
 Date
 2024-01-02    980.921367    981.560909    964.441495    966.409241
 2024-01-03    968.819839    972.066609    959.374622    968.180298
 2024-01-04    970.492381    973.198032    966.064952    971.230286
 2024-01-05    972.066533    982.200413    967.934255    977.674622
 2024-01-08    977.969745    982.102023    964.490673    966.163269
 ...                  ...           ...           ...           ...
 2025-12-29   1352.099976   1355.699951   1341.500000   1343.300049
 2025-12-30   1343.300049   1347.099976   1338.099976   1342.500000
 2025-12-31   1342.800049   1350.000000   1339.500000   1342.900024
 2026-01-01   1343.900024   1348.400024   1336.000000   1338.000000
 2026-01-02   1338.000000   1350.599976   1336.300049   1350.400024

             ICICIBANK.NS
 Date
 2024-01-02      16263825
 2024-01-03      16826752
 2024-01-04      22789140
 2024-01-05      14875499
 2024-01-08       8393164
 ...                  ...
 2025-12-29       6057201
 2025-12-30      18621277
 2025-12-31       6150634
 2026-01-01       4179311
 2026-01-02       4302976

 [498 rows x 5 columns],
 'HDFCBANK.NS':             HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS  HDFCBANK.NS
 Date
 2024-01-02   826.781764   828.728507   821.866191   826.927734     29242092
 2024-01-03   828.339118   829.653145   812.254130   814.176575     28389762
 2024-01-04   816.658698   824.907997   813.105868   822.912598     26734056
 2024-01-05   821.111889   829.750561   811.840501   818.702759     31889470
 2024-01-08   816.902037   818.775765   807.898350   809.577393     17998470
 ...                 ...          ...          ...          ...          ...
 2025-12-29   993.099976   997.400024   987.200012   991.700012     13545749
 2025-12-30   990.200012   995.000000   982.200012   990.900024     33155849
 2025-12-31   991.000000   997.599976   987.599976   991.200012     10963454
 2026-01-01   993.500000   997.549988   989.500000   991.150024      7132074
 2026-01-02   991.150024  1000.849976   988.799988   998.799988      6893793

 [498 rows x 5 columns]}

In [37]:
out['SBIN.NS'].reset_index()

          Date     SBIN.NS     SBIN.NS     SBIN.NS     SBIN.NS   SBIN.NS
0   2024-01-02  618.355831  624.767434  611.124727  616.523987  15164482
1   2024-01-03  616.427515  624.767412  613.004804  620.380554  14571772
2   2024-01-04  619.464591  623.224788  615.752647  619.705627  13883388
3   2024-01-05  621.875025  628.383019  614.884957  618.934387  15984585
4   2024-01-08  617.054239  621.874975  602.640226  604.520325  14739531
..         ...         ...         ...         ...         ...       ...
493 2025-12-29  966.900024  968.900024  961.450012  965.049988   5267233
494 2025-12-30  963.000000  976.200012  959.500000  973.450012  15030644
495 2025-12-31  975.250000  985.650024  973.500000  982.200012   5807630
496 2026-01-01  983.200012  987.650024  980.349976  984.750000   4328348
497 2026-01-02  984.500000  993.000000  983.950012  990.700012   3579955

[498 rows x 6 columns]

In [36]:
out[tickers[1]]

,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS,ICICIBANK.NS
Date,,,,,
2024-01-02,980.921367,981.560909,964.441495,966.409241,16263825
2024-01-03,968.819839,972.066609,959.374622,968.180298,16826752
2024-01-04,970.492381,973.198032,966.064952,971.230286,22789140
2024-01-05,972.066533,982.200413,967.934255,977.674622,14875499
2024-01-08,977.969745,982.102023,964.490673,966.163269,8393164
...,...,...,...,...,...
2025-12-29,1352.099976,1355.699951,1341.500000,1343.300049,6057201
2025-12-30,1343.300049,1347.099976,1338.099976,1342.500000,18621277
2025-12-31,1342.800049,1350.000000,1339.500000,1342.900024,6150634
2026-01-01,1343.900024,1348.400024,1336.000000,1338.000000,4179311
2026-01-02,1338.000000,1350.599976,1336.300049,1350.400024,4302976

In [52]:
sbin = out['SBIN.NS'].rename(index={0: "Close", 1: "High", 2: "Low", 3:"Open",'SBIN.NS':"Volume"})
sbin.head()
#sbin.to_returns()
#stats = out.calc_stats()
#stats.display()

               SBIN.NS     SBIN.NS     SBIN.NS     SBIN.NS   SBIN.NS
Date
2024-01-02  618.355831  624.767434  611.124727  616.523987  15164482
2024-01-03  616.427515  624.767412  613.004804  620.380554  14571772
2024-01-04  619.464591  623.224788  615.752647  619.705627  13883388
2024-01-05  621.875025  628.383019  614.884957  618.934387  15984585
2024-01-08  617.054239  621.874975  602.640226  604.520325  14739531

# Another Way

In [42]:
tickers = ['AAPL', 'MSFT', 'NVDA']

separated_df = {}
for ticker in tickers:
    tmp = out.loc[:, ticker].rename_axis(None, axis=1)
    separated_df[ticker] = tmp

AttributeError: 'dict' object has no attribute 'loc'